-- The complete ChemBattle result is stored per run. Points are generated by
-- PostgreSQL so clients cannot choose their own leaderboard ranking.
alter table public.matches
  add column if not exists enemies_defeated integer,
  add column if not exists compounds_discovered integer,
  add column if not exists highest_combo integer;

alter table public.matches
  add column if not exists leaderboard_points integer
  generated always as (
    coalesce(score, 0)
    + coalesce(waves_cleared, 0) * 1000
    + coalesce(compounds_discovered, 0) * 500
    + coalesce(enemies_defeated, 0) * 100
    + coalesce(highest_combo, 0) * 200
    - coalesce(turns_played, 0) * 50
  ) stored;

alter table public.matches
  drop constraint if exists matches_enemies_defeated_nonnegative,
  drop constraint if exists matches_compounds_discovered_nonnegative,
  drop constraint if exists matches_highest_combo_nonnegative;

alter table public.matches
  add constraint matches_enemies_defeated_nonnegative
    check (enemies_defeated is null or enemies_defeated >= 0),
  add constraint matches_compounds_discovered_nonnegative
    check (compounds_discovered is null or compounds_discovered >= 0),
  add constraint matches_highest_combo_nonnegative
    check (highest_combo is null or highest_combo >= 0);

create index if not exists idx_matches_leaderboard_points
  on public.matches (leaderboard_points desc, score desc, turns_played asc, match_date asc)
  where lower(winner) = 'player' and score is not null;
